// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxIp66TRsClQqFyPiTm4JiCTmYzUuNk8',
    appId: '1:828509550581:ios:84a178ca92d2e66468d2bc',
    messagingSenderId: '828509550581',
    projectId: 'skill-path-ai-c172e',
    storageBucket: 'skill-path-ai-c172e.firebasestorage.app',
    iosBundleId: 'com.example.skillPathAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxIp66TRsClQqFyPiTm4JiCTmYzUuNk8',
    appId: '1:828509550581:ios:84a178ca92d2e66468d2bc',
    messagingSenderId: '828509550581',
    projectId: 'skill-path-ai-c172e',
    storageBucket: 'skill-path-ai-c172e.firebasestorage.app',
    iosBundleId: 'com.example.skillPathAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYjD0dLtF3repAnF1_HrKtEZAo8YotZcM',
    appId: '1:828509550581:web:ed5ac739f686ec5868d2bc',
    messagingSenderId: '828509550581',
    projectId: 'skill-path-ai-c172e',
    authDomain: 'skill-path-ai-c172e.firebaseapp.com',
    storageBucket: 'skill-path-ai-c172e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYjD0dLtF3repAnF1_HrKtEZAo8YotZcM',
    appId: '1:828509550581:web:ed5ac739f686ec5868d2bc',
    messagingSenderId: '828509550581',
    projectId: 'skill-path-ai-c172e',
    authDomain: 'skill-path-ai-c172e.firebaseapp.com',
    storageBucket: 'skill-path-ai-c172e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm9PVDrxZfHJGTDQGTKoZiTPHghngd3gM',
    appId: '1:828509550581:android:099381e971e70bc368d2bc',
    messagingSenderId: '828509550581',
    projectId: 'skill-path-ai-c172e',
    storageBucket: 'skill-path-ai-c172e.firebasestorage.app',
  );

}